# Add application configuration variables here, as shown below.
#
ACCESS_KEY_ID: AKIAJDJPNRVJ27CVWBDQ
SECRET_ACCESS_KEY: ASK_ELIZA
GITHUB_CLIENT_ID: 6420f58670f870ffcda8
GITHUB_CLIENT_SECRET: ASK_ELIZA
CODECLIMATE_REPO_TOKEN: 2c71be9face3f96ccc6cc512a4d84a5a410c648219b21706135762b346b1e9f8
